Repository zuri-training/Team-dove, pull requests merged in 2022-12, with the labels that each got.

#12 Created the navbar and added extra resources
  public/css/style.css
  public/images/favicon.png
  resources/views/home.blade.php
  resources/views/layout/footer.blade.php
  resources/views/layout/navbar.blade.php
  resources/views/layout/topbar.blade.php
  resources/views/welcome.blade.php
  routes/web.php
Labels: enhancement

#14 Designed the home page
  public/css/style.css
  public/images/c-plus-logo.png
  public/images/laravel-logo.png
  public/images/python-logo.png
  resources/views/home.blade.php
Labels: enhancement

#16 Fine-tuned footer with bootstrap styling
  .env.example
  composer.lock
  public/css/footer.css
  public/css/style.css
  resources/views/layout/footer.blade.php
Labels: fixed

#17 Register page
  .env.example
  app/Http/Controllers/RegisterController.php
  public/css/style.css
  resources/views/auth/register.blade.php
  resources/views/layout/navbar.blade.php
  routes/web.php
Labels: enhancement

#20 Login Page - Frontend Design Update
  app/Http/Controllers/LoginController.php
  resources/views/auth/login.blade.php
  resources/views/home.blade.php
  resources/views/layout/navbar.blade.php
  routes/web.php
Labels: enhancement

#19 initial commit about-us page
  public/css/style.css
  resources/views/about.blade.php
  resources/views/layout/navbar.blade.php
  routes/web.php
Labels: enhancement

#24 Reset password page design
  app/Http/Controllers/ResetPasswordController.php
  resources/views/auth/resetPassword.blade.php
  routes/web.php
Labels: enhancement

#25 Blade and Controller update
  app/Http/Controllers/RegisterController.php
  resources/views/auth/register.blade.php
  routes/web.php
Labels: enhancement, fixed

#26 Blade and Controller update - confirm email
  app/Http/Controllers/ConfirmEmailController.php
  resources/views/auth/confirmEmail.blade.php
  routes/web.php
Labels: enhancement, fixed

#29 Configured DB Migrations
  database/migrations/2014_10_12_000000_create_users_table.php
  database/migrations/2022_12_16_122925_create_categories_table.php
  database/migrations/2022_12_16_123911_create_comments_table.php
  database/migrations/2022_12_16_124124_create_libraries_table.php
  database/migrations/2022_12_16_131512_create_reactions_table.php
Labels: enhancement
